echo stoping services
docker stop mongodb
docker rm mongodb

mkdir data
docker run -d -e MONGO_INITDB_ROOT_USERNAME='restheart' -p 27017:27017 -e MONGO_INITDB_ROOT_PASSWORD='R3ste4rt!'  --name mongodb -v "$PWD/data:/data/db" -v "$PWD/import:/home" mongo:3.6 --bind_ip_all --auth
sleep 20
docker  exec  mongodb mongoimport  -u restheart -p R3ste4rt! --authenticationDatabase admin --db myflix --collection videos --drop --file /home/videos.json
docker  exec  mongodb mongoimport  -u restheart -p R3ste4rt! --authenticationDatabase admin --db myflix --collection categories --drop --file /home/categories.json


